[package]
name = "roku-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
confy = "0.6.1"
crossterm = { version = "0.28.1", features = ["serde"] }
reqwest = { version = "0.12.9", features = ["blocking"] }
ron = "0.8.1"
serde = { version = "1.0.216", features = ["serde_derive"] }
url = "2.5.4"
